export const categoryMapping = {
  "グルメ・レストラン": {
    yahoo: [
      "0101",
      "0102",
      "0103",
      "0104",
      "0105",
      "0106",
      "0107",
      "0108",
      "0109",
      "0110",
      "0111",
      "0112",
      "0113",
      "0114",
      "0115",
      "0116",
      "0117",
      "0118",
      "0119",
      "0120",
      "0121",
      "0122",
      "0123",
      "0124",
      "0125",
      "0126",
      "0127",
      "0128",
    ],
    google: [
      "restaurant",
      "japanese_restaurant",
      "ramen_restaurant",
      "sushi_restaurant",
      "barbecue_restaurant",
      "buffet_restaurant",
      "fast_food_restaurant",
      "steak_house",
      "pizza_restaurant",
      "french_restaurant",
      "italian_restaurant",
      "korean_restaurant",
      "thai_restaurant",
      "turkish_restaurant",
      "chinese_restaurant",
      "mexican_restaurant",
      "spanish_restaurant",
      "indian_restaurant",
      "vietnamese_restaurant",
      "mediterranean_restaurant",
      "vegetarian_restaurant",
      "vegan_restaurant",
      "hamburger_restaurant",
      "bar",
      "pub",
      "cafe",
      "coffee_shop",
      "tea_house",
      "bakery",
      "dessert_shop",
      "donut_shop",
      "ice_cream_shop",
      "sandwich_shop",
    ],
  },
  ショッピング: {
    yahoo: [
      "0201",
      "0202",
      "0203",
      "0204",
      "0205",
      "0206",
      "0207",
      "0208",
      "0209",
      "0210",
      "0211",
    ],
    google: [
      "convenience_store",
      "grocery_store",
      "supermarket",
      "department_store",
      "shopping_mall",
      "store",
      "clothing_store",
      "book_store",
      "electronics_store",
      "liquor_store",
      "pet_store",
      "furniture_store",
      "jewelry_store",
      "gift_shop",
      "shoe_store",
      "hardware_store",
      "home_goods_store",
      "bicycle_store",
      "cell_phone_store",
      "auto_parts_store",
      "discount_store",
    ],
  },
  "レジャー・エンタメ": {
    yahoo: ["0301", "0302", "0303", "0304", "0305", "0306", "0307", "0308"],
    google: [
      "zoo",
      "aquarium",
      "museum",
      "amusement_park",
      "movie_theater",
      "theme_park",
      "art_gallery",
      "concert_hall",
      "historical_place",
      "tourist_attraction",
      "cultural_landmark",
      "night_club",
      "casino",
      "bowling_alley",
      "park",
      "observation_deck",
      "plaza",
    ],
  },
  "暮らし・生活": {
    yahoo: [
      "0401",
      "0402",
      "0403",
      "0404",
      "0405",
      "0406",
      "0407",
      "0408",
      "0409",
      "0410",
      "0411",
      "0412",
      "0413",
      "0414",
      "0415",
      "0416",
      "0417",
      "0418",
      "0419",
      "0420",
      "0421",
      "0422",
      "0423",
      "0424",
      "0425",
    ],
    google: [
      "beauty_salon",
      "hair_salon",
      "nail_salon",
      "spa",
      "hospital",
      "pharmacy",
      "doctor",
      "dentist",
      "chiropractor",
      "laundry",
      "post_office",
      "bank",
      "atm",
      "insurance_agency",
      "real_estate_agency",
      "storage",
    ],
  },
  交通: {
    yahoo: ["0306"],
    google: [
      "bus_station",
      "train_station",
      "subway_station",
      "taxi_stand",
      "airport",
      "parking",
      "gas_station",
      "car_rental",
      "car_repair",
      "car_wash",
      "electric_vehicle_charging_station",
    ],
  },
  教育: {
    yahoo: ["0406", "0407", "0408"],
    google: [
      "primary_school",
      "secondary_school",
      "university",
      "preschool",
      "library",
    ],
  },
  宿泊施設: {
    yahoo: ["0304"],
    google: [
      "hotel",
      "motel",
      "guest_house",
      "hostel",
      "bed_and_breakfast",
      "resort_hotel",
      "inn",
    ],
  },
  宗教施設: {
    yahoo: ["0424"],
    google: ["church", "mosque", "synagogue", "hindu_temple"],
  },
};

export const majorGoogleOptions = {
  "グルメ・レストラン": ["restaurant", "cafe", "bar"],
  ショッピング: ["shopping_mall", "supermarket", "convenience_store"],
  "レジャー・エンタメ": ["tourist_attraction", "museum", "park"],
  "暮らし・生活": ["hospital", "pharmacy", "bank"],
  交通: ["train_station", "bus_station", "parking"],
  教育: ["university", "library", "primary_school"],
  宿泊施設: ["hotel", "guest_house", "hostel"],
  宗教施設: ["church", "mosque", "synagogue"],
} as const;

export const radius = 3000;
