export const categoryMapping = {
  "グルメ・レストラン": {
    yahoo: ["01"],
    google: [
      "restaurant",
      "japanese_restaurant",
      "ramen_restaurant",
      "sushi_restaurant",
      "barbecue_restaurant",
      "buffet_restaurant",
      "fast_food_restaurant",
      "steak_house",
      "pizza_restaurant",
      "french_restaurant",
      "italian_restaurant",
      "korean_restaurant",
      "thai_restaurant",
      "turkish_restaurant",
      "chinese_restaurant",
      "mexican_restaurant",
      "spanish_restaurant",
      "indian_restaurant",
      "vietnamese_restaurant",
      "mediterranean_restaurant",
      "vegetarian_restaurant",
      "vegan_restaurant",
      "hamburger_restaurant",
      "bar",
      "pub",
      "cafe",
      "coffee_shop",
      "tea_house",
      "bakery",
      "dessert_shop",
      "donut_shop",
      "ice_cream_shop",
      "sandwich_shop",
    ],
  },
  ショッピング: {
    yahoo: ["02"],
    google: [
      "convenience_store",
      "grocery_store",
      "supermarket",
      "department_store",
      "shopping_mall",
      "store",
      "clothing_store",
      "book_store",
      "electronics_store",
      "liquor_store",
      "pet_store",
      "furniture_store",
      "jewelry_store",
      "gift_shop",
      "shoe_store",
      "hardware_store",
      "home_goods_store",
      "bicycle_store",
      "cell_phone_store",
      "auto_parts_store",
      "discount_store",
    ],
  },
  "レジャー・エンタメ": {
    yahoo: ["03"],
    google: [
      "zoo",
      "aquarium",
      "museum",
      "amusement_park",
      "movie_theater",
      "theme_park",
      "art_gallery",
      "concert_hall",
      "historical_place",
      "tourist_attraction",
      "cultural_landmark",
      "night_club",
      "casino",
      "bowling_alley",
      "park",
      "observation_deck",
      "plaza",
    ],
  },
  "暮らし・生活": {
    yahoo: ["04"],
    google: [
      "beauty_salon",
      "hair_salon",
      "nail_salon",
      "spa",
      "hospital",
      "pharmacy",
      "doctor",
      "dentist",
      "chiropractor",
      "laundry",
      "post_office",
      "bank",
      "atm",
      "insurance_agency",
      "real_estate_agency",
      "storage",
    ],
  },
  交通: {
    yahoo: ["0306"],
    google: [
      "bus_station",
      "train_station",
      "subway_station",
      "taxi_stand",
      "airport",
      "parking",
      "gas_station",
      "car_rental",
      "car_repair",
      "car_wash",
      "electric_vehicle_charging_station",
    ],
  },
  教育: {
    yahoo: ["0406", "0407", "0408"],
    google: [
      "primary_school",
      "secondary_school",
      "university",
      "preschool",
      "library",
    ],
  },
  宿泊施設: {
    yahoo: ["0304"],
    google: [
      "hotel",
      "motel",
      "guest_house",
      "hostel",
      "bed_and_breakfast",
      "resort_hotel",
      "inn",
    ],
  },
  宗教施設: {
    yahoo: ["0424"],
    google: ["church", "mosque", "synagogue", "hindu_temple"],
  },
};
